apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: Say hello

runs:
  using: composite
  steps:
      - name: Create file
        id: step3
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Hello world! I'm $(whoami) on $(hostname)"
