apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Custom action in runner
on:
  workflow_dispatch:

jobs:
  hello_custom_action:
    steps:
      - name: Say hello
        uses: mluzcabrera/test_edge_runners_v0.4@main