apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflowavf
on:
  workflow_dispatch:
jobs:
  caller-job:
    uses: ./.cloudbees/workflows/reusable-edge.yaml
    with:
      runner_label: my-label-3
  consume:
    needs: [caller-job]
    steps:
      - uses: docker://alpine:3.17
        run: echo "got ${{ needs.caller-job.outputs.final_greeting }}"
