apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflowavf
on:
  workflow_dispatch:
    inputs:
      label:
        type: string
        default: my-label-3
jobs:
  simple-check:
    environment: mlcbedgerunnersenv
    steps:
      - run: echo "vars.envlabel-> ${{ vars.envlabel}} and inputs.label-> ${{ inputs.label }} and vars. varslabel-> ${{vars.varslabel}}"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
  caller-job:
    needs: simple-check
    uses: ./.cloudbees/workflows/reusable-edge.yaml
    with:
      runner_label: ${{ inputs.label }}
  consume:
    needs:
      - caller-job
    steps:
      - uses: docker://alpine:3.17
        run: echo "got ${{ needs.caller-job.outputs.final_greeting }}"
  caller-job-vars:
    uses: ./.cloudbees/workflows/reusable-edge.yaml
    with:
      runner_label: ${{ vars.varslabel }}
    needs:
      - simple-check
  caller-job-env:
    environment: mlcbedgerunnersenv
    uses: ./.cloudbees/workflows/reusable-edge.yaml
    with:
      runner_label: ${{ vars.envlabel }}
    needs:
      - simple-check
  
