apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: test action
on:
  workflow_dispatch:
jobs:
  hello_action:
    steps:
      - name: Say hello
        uses: cloudbees-io/checkout@v1
    runs-on:
      - my-label-3
